<?php
    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\SMTP;
    use PHPMailer\PHPMailer\Exception;
    require __DIR__ . '/vendor/autoload.php';
    include "./phpqrcode/qrlib.php";
    include("../api-yitp/conn.php");
    use Picqer\Barcode\BarcodeGeneratorPNG;
    
    //Verifying the Signature
    $recievedJwt = $_GET['token'];
    $secret_key = 'HOMEPACKYITP2020';
    // Split a string by '.' 
    $jwt_values = explode('.', $recievedJwt);
    // extracting the signature from the original JWT 
    $recieved_signature = $jwt_values[2];
    // concatenating the first two arguments of the $jwt_values array, representing the header and the payload
    $recievedHeaderAndPayload = $jwt_values[0] . '.' . $jwt_values[1];
    // creating the Base 64 encoded new signature generated by applying the HMAC method to the concatenated header and payload values
    $resultedsignature = base64_encode(hash_hmac('sha256', $recievedHeaderAndPayload, $secret_key, true));
    // checking if the created signature is equal to the received signature
    $recieved_signature = str_replace(" ", "+", $recieved_signature);
    if($resultedsignature == $recieved_signature) {
        $order = $_POST["orden_compra"];
        $sql = "SELECT id, data, total FROM pagos WHERE orden_compra = '$order'";
        $result = $conn->query($sql);
        if ($result->num_rows > 0) {
          while($row = $result->fetch_assoc()) {
            $arr = json_decode($row["data"], true);
            $id_pago = $row["id"];
            $total_pago = $row['total'];
            foreach ($arr as $row)
            {
                $direccion = $row["direccion"];
                $rut = $row["rut_destinatario"];
                $nombre = $row["nombre_destinatario"];
                $telefono = $row["telefono_destinatario"];
                $email = $row["email_destinatario"];
                $detalle = $row["detalle"];
                $total = $row["total"];
                $origen = $row["origen"];
                $destino = $row["destino"];
                $id_usuario = $row["id_usuario"];
                $peso = $row["peso"];
                $referencia = $row["referencia"];
                $rut_remitente = $row["rut_remitente"];
                $nombre_remitente = $row["nombre_remitente"];
                $telefono_remitente = $row["telefono_remitente"];
                $email_remitente = $row["email_remitente"];
                $direccion_remitente = $row["direccion_remitente"];
                $uid = hexdec( uniqid() );
                
            	//Declaramos una carpeta temporal para guardar la imagenes generadas
            	$dir = dirname(__DIR__).'/khipu/temp/';
            	
            	//Si no existe la carpeta la creamos
            	if (!file_exists($dir))
                    mkdir($dir);
            	
                //Declaramos la ruta y nombre del archivo a generar
            	$filename = $dir.$uid.'.png';
             
                //Parametros de Condiguración
            	
            	$tamaño = 10; //Tamaño de Pixel
            	$level = 'L'; //Precisión Baja
            	$framSize = 3; //Tamaño en blanco
            	$contenido = $uid; //Texto
            	
                    //Enviamos los parametros a la Función para generar código QR 
            	QRcode::png($contenido, $filename, $level, $tamaño, $framSize); 
            	
            	$qr = 'temp/'.$uid.'.png';;
            	
            	// BARCODE
            	# Crear generador
                $generador = new BarcodeGeneratorPNG();
                # Ajustes
                $texto = $contenido;
                $tipo = $generador::TYPE_CODE_128;
                $imagen = $generador->getBarcode($texto, $tipo);
                # Aquí se guarda la imagen
                $nombreArchivo = $contenido.".png";
                # Escribir los datos
                $dir_to_save = dirname(__DIR__)."/khipu/barcode/";
                if (!is_dir($dir_to_save)) {
                  mkdir($dir_to_save);
                }
                file_put_contents($dir_to_save.$nombreArchivo, $imagen);
            	// END BARCODE
                
                include("../api-yitp/conn.php");
                $sql = "
                INSERT INTO despachos (rut_destinatario, nombre_destinatario, telefono_destinatario, email_destinatario, fecha_ingreso, detalle, numero_seguimiento, total, origen, destino, id_usuario, peso, orden_compra, qr, referencia, direccion, rut_remitente, nombre_remitente, telefono_remitente, email_remitente, direccion_remitente, retirado, barcode, id_pago, entregado, centro_distribucion, a_destino) 
                VALUES ('$rut', '$nombre', '$telefono', '$email', NOW(), '$detalle', '$uid', '$total', $origen, $destino, $id_usuario, '$peso', '$order', '$qr', '$referencia', '$direccion', '$rut_remitente', '$nombre_remitente', '$telefono_remitente', '$email_remitente', '$direccion_remitente', 0, '".'barcode/'.$nombreArchivo."', $id_pago, 0, 0, 0);";
                    
                if (!$conn -> query($sql)) {
                  $myObj->status = 0;
                    $myObj->mesagge = $conn -> error;
                    $myJSON = json_encode($myObj);
                    echo $myJSON;
                  die;
                } else {
                    sendMailDespacho($email_remitente, $email, $total, $uid);
                }
                
                $estado = "ORDEN DE TRANSPORTE CREADA";
                $fk_id_despacho = mysqli_insert_id($conn);

                $sql = "INSERT INTO seguimiento (fecha, estado, foto, fk_id_despacho, nombre_recepcion, apellido_recepcion, rut_recepcion) VALUES (NOW(), '$estado', null, $fk_id_despacho, null, null, null)";
                
                if (!$conn -> query($sql)) {
                  $myObj->status = 0;
                    $myObj->mesagge = $conn -> error;
                    $myJSON = json_encode($myObj);
                    echo $myJSON;
                  die;
                }
            }
          }
        }
        $conn->close();
        $myObj->status = 1;
        $myObj->mesagge = "Despachos registrados correctamente.";
        $myJSON = json_encode($myObj);
        echo $myJSON;
    } else {
        echo "No permitido";
    }

function sendMailDespacho($remitente_email, $destinatario_email, $ammount, $seguimiento)
{
    $mail = new PHPMailer(true);

    try {
        //Server settings
        // $mail->SMTPDebug  = SMTP::DEBUG_SERVER;                      // Enable verbose debug output
        $mail->isSMTP();                                            // Send using SMTP
        $mail->Host       = 'mail.homepackchile.cl';                    // Set the SMTP server to send through
        $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
        $mail->Username   = 'no-reply@homepackchile.cl';                     // SMTP username
        $mail->Password   = 'homepackchile';                               // SMTP password
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;         // Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` encouraged
        $mail->Port       = 587;                                    // TCP port to connect to, use 465 for `PHPMailer::ENCRYPTION_SMTPS` above
    
        //Recipients
        $mail->setFrom('no-reply@homepackchile.cl', utf8_decode('Home Pack Chile - Información'));
        $mail->addAddress($remitente_email);     // Add a recipient
        $mail->AddCC($destinatario_email);
        
        // Content
        $mail->isHTML(true);                                  // Set email format to HTML
        $mail->Subject = utf8_decode('Nuevo despacho - Home Pack Chile');
        $mail->Body    = utf8_decode('
            <html>

            <head>
                <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
                <meta content="width=device-width" name="viewport" />
                <meta content="IE=edge" http-equiv="X-UA-Compatible" />
                <title></title>
                <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet" type="text/css" />
                <style type="text/css">
                    body {
                        margin: 0;
                        padding: 0;
                    }
            
                    table,
                    td,
                    tr {
                        vertical-align: top;
                        border-collapse: collapse;
                    }
            
                    * {
                        line-height: inherit;
                    }
            
                    a[x-apple-data-detectors=true] {
                        color: inherit !important;
                        text-decoration: none !important;
                    }
                </style>
                <style id="media-query" type="text/css">
                    @media (max-width: 660px) {
            
                        .block-grid,
                        .col {
                            min-width: 320px !important;
                            max-width: 100% !important;
                            display: block !important;
                        }
            
                        .block-grid {
                            width: 100% !important;
                        }
            
                        .col {
                            width: 100% !important;
                        }
            
                        .col_cont {
                            margin: 0 auto;
                        }
            
                        img.fullwidth,
                        img.fullwidthOnMobile {
                            max-width: 100% !important;
                        }
            
                        .no-stack .col {
                            min-width: 0 !important;
                            display: table-cell !important;
                        }
            
                        .no-stack.two-up .col {
                            width: 50% !important;
                        }
            
                        .no-stack .col.num2 {
                            width: 16.6% !important;
                        }
            
                        .no-stack .col.num3 {
                            width: 25% !important;
                        }
            
                        .no-stack .col.num4 {
                            width: 33% !important;
                        }
            
                        .no-stack .col.num5 {
                            width: 41.6% !important;
                        }
            
                        .no-stack .col.num6 {
                            width: 50% !important;
                        }
            
                        .no-stack .col.num7 {
                            width: 58.3% !important;
                        }
            
                        .no-stack .col.num8 {
                            width: 66.6% !important;
                        }
            
                        .no-stack .col.num9 {
                            width: 75% !important;
                        }
            
                        .no-stack .col.num10 {
                            width: 83.3% !important;
                        }
            
                        .video-block {
                            max-width: none !important;
                        }
            
                        .mobile_hide {
                            min-height: 0px;
                            max-height: 0px;
                            max-width: 0px;
                            display: none;
                            overflow: hidden;
                            font-size: 0px;
                        }
            
                        .desktop_hide {
                            display: block !important;
                            max-height: none !important;
                        }
                    }
                </style>
            </head>
            
            <body class="clean-body" style="margin: 0; padding: 0; -webkit-text-size-adjust: 100%; background-color: #f8f8f9;">
                <table bgcolor="#f8f8f9" cellpadding="0" cellspacing="0" class="nl-container" role="presentation"
                    style="table-layout: fixed; vertical-align: top; min-width: 320px; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f8f8f9; width: 100%;"
                    valign="top" width="100%">
                    <tbody>
                        <tr style="vertical-align: top;" valign="top">
                            <td style="word-break: break-word; vertical-align: top;" valign="top">
                                <div style="background-color:purple;">
                                    <div class="block-grid"
                                        style="min-width: 320px; max-width: 640px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: purple;">
                                        <div style="border-collapse: collapse;display: table;width: 100%;background-color:#1aa19c;">
                                            <div class="col num12"
                                                style="min-width: 320px; max-width: 640px; display: table-cell; vertical-align: top; width: 640px;">
                                                <div class="col_cont" style="width:100% !important;">
                                                    <div
                                                        style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:0px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;">
                                                        <table border="0" cellpadding="0" cellspacing="0" class="divider"
                                                            role="presentation"
                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                            valign="top" width="100%">
                                                            <tbody>
                                                                <tr style="vertical-align: top;" valign="top">
                                                                    <td class="divider_inner"
                                                                        style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;"
                                                                        valign="top">
                                                                        <table align="center" border="0" cellpadding="0"
                                                                            cellspacing="0" class="divider_content"
                                                                            role="presentation"
                                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 4px solid purple; width: 100%;"
                                                                            valign="top" width="100%">
                                                                            <tbody>
                                                                                <tr style="vertical-align: top;" valign="top">
                                                                                    <td style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                                                        valign="top"><span></span></td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div style="background-color:#f8f8f9;">
                                    <div class="block-grid"
                                        style="min-width: 320px; max-width: 640px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #fff;">
                                        <div style="border-collapse: collapse;display: table;width: 100%;background-color:#fff;">
                                            <div class="col num12"
                                                style="min-width: 320px; max-width: 640px; display: table-cell; vertical-align: top; width: 640px;">
                                                <div class="col_cont" style="width:100% !important;">
                                                    <div
                                                        style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:0px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;">
                                                        <div align="center" class="img-container center fixedwidth"
                                                            style="padding-right: 0px;padding-left: 0px;">
                                                            <div style="font-size:1px;line-height:22px"> </div><img align="center"
                                                                alt="" border="0" class="center fixedwidth"
                                                                src="https://github.com/xjonatanx/logo-homepackchile/blob/main/logo.png?raw=true"
                                                                style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; width: 100%; max-width: 128px; display: block;"
                                                                title="" width="128" />
                                                            <div style="font-size:1px;line-height:25px"> </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div style="background-color:transparent;">
                                    <div class="block-grid"
                                        style="min-width: 320px; max-width: 640px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #f8f8f9;">
                                        <div style="border-collapse: collapse;display: table;width: 100%;background-color:#f8f8f9;">
                                            <div class="col num12"
                                                style="min-width: 320px; max-width: 640px; display: table-cell; vertical-align: top; width: 640px;">
                                                <div class="col_cont" style="width:100% !important;">
                                                    <div
                                                        style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">
                                                        <table border="0" cellpadding="0" cellspacing="0" class="divider"
                                                            role="presentation"
                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                            valign="top" width="100%">
                                                            <tbody>
                                                                <tr style="vertical-align: top;" valign="top">
                                                                    <td class="divider_inner"
                                                                        style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 0px; padding-right: 20px; padding-bottom: 5px; padding-left: 20px;"
                                                                        valign="top">
                                                                        <table align="center" border="0" cellpadding="0"
                                                                            cellspacing="0" class="divider_content"
                                                                            role="presentation"
                                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid #BBBBBB; width: 100%;"
                                                                            valign="top" width="100%">
                                                                            <tbody>
                                                                                <tr style="vertical-align: top;" valign="top">
                                                                                    <td style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                                                        valign="top"><span></span></td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div style="background-color:transparent;">
                                    <div class="block-grid"
                                        style="min-width: 320px; max-width: 640px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #fff;">
                                        <div style="border-collapse: collapse;display: table;width: 100%;background-color:#fff;">
                                            <div class="col num12"
                                                style="min-width: 320px; max-width: 640px; display: table-cell; vertical-align: top; width: 640px;">
                                                <div class="col_cont" style="width:100% !important;">
                                                    <div
                                                        style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:0px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;">
                                                        <br>
                                                        <div
                                                            style="color:#555555;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.2;padding-top:10px;padding-right:40px;padding-bottom:10px;padding-left:40px;">
                                                            <div
                                                                style="line-height: 1.2; font-size: 12px; color: #555555; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 14px;">
                                                                <p
                                                                    style="font-size: 30px; line-height: 1.2; text-align: center; word-break: break-word; mso-line-height-alt: 36px; margin: 0;">
                                                                    <span style="font-size: 27px; color: #2b303a;"><strong>Nuevo despacho creado</strong></span></p>
                                                            </div>
                                                        </div>
                                                        <div
                                                            style="color:#555555;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.5;padding-top:10px;padding-right:40px;padding-bottom:10px;padding-left:40px;">
                                                            <div
                                                                style="line-height: 1.5; font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; color: #555555; mso-line-height-alt: 18px;">
                                                                <p
                                                                    style="font-size: 15px; line-height: 1.5; text-align: center; word-break: break-word; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 23px; margin: 0;">
                                                                    <span style="color: #808389; font-size: 15px;">Le informamos que
                                                                        su despacho se ha ingresado correctamente, se recuerda que el tipo de envío es <b>POR PAGAR</b>, esto significa que el valor será costeado por el destinatario del despacho. A continuación se detalla la información de su despacho.</span></p>
                                                            </div>
                                                        </div>
                                                        <table border="0" cellpadding="0" cellspacing="0" class="divider"
                                                            role="presentation"
                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                            valign="top" width="100%">
                                                            <tbody>
                                                                <tr style="vertical-align: top;" valign="top">
                                                                    <td class="divider_inner"
                                                                        style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 50px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;"
                                                                        valign="top">
                                                                        <table align="center" border="0" cellpadding="0"
                                                                            cellspacing="0" class="divider_content"
                                                                            role="presentation"
                                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid #BBBBBB; width: 100%;"
                                                                            valign="top" width="100%">
                                                                            <tbody>
                                                                                <tr style="vertical-align: top;" valign="top">
                                                                                    <td style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                                                        valign="top"><span></span></td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div style="background-color:transparent;">
                                    <div class="block-grid two-up no-stack"
                                        style="min-width: 320px; max-width: 640px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #fff;">
                                        <div style="border-collapse: collapse;display: table;width: 100%;background-color:#fff;">
                                            <div class="col num6"
                                                style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 318px; background-color: #f9f3fa; width: 292px;">
                                                <div class="col_cont" style="width:100% !important;">
                                                    <div
                                                        style="border-top:0px solid transparent; border-left:20px solid #FFF; border-bottom:0px solid transparent; border-right:8px solid #FFF; padding-top:0px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;">
                                                        <table border="0" cellpadding="0" cellspacing="0" class="divider"
                                                            role="presentation"
                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                            valign="top" width="100%">
                                                            <tbody>
                                                                <tr style="vertical-align: top;" valign="top">
                                                                    <td class="divider_inner"
                                                                        style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;"
                                                                        valign="top">
                                                                        <table align="center" border="0" cellpadding="0"
                                                                            cellspacing="0" class="divider_content" height="1"
                                                                            role="presentation"
                                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 4px solid PURPLE; height: 1px; width: 100%;"
                                                                            valign="top" width="100%">
                                                                            <tbody>
                                                                                <tr style="vertical-align: top;" valign="top">
                                                                                    <td height="1"
                                                                                        style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                                                        valign="top"><span></span></td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                        <div
                                                            style="color:#555555;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.5;padding-top:35px;padding-right:5px;padding-bottom:40px;padding-left:5px;">
                                                            <div
                                                                style="line-height: 1.5; font-size: 12px; color: #555555; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 18px;">
                                                                <p
                                                                    style="font-size: 12px; line-height: 1.5; text-align: center; word-break: break-word; mso-line-height-alt: 18px; margin: 0;">
                                                                    <span style="color: #a2a9ad; font-size: 12px;"><strong>NÚMERO DE SEGUIMIENTO</strong></span></p>
                                                                <p
                                                                    style="font-size: 20px; line-height: 1.5; text-align: center; word-break: break-word; mso-line-height-alt: 30px; margin: 0;">
                                                                    <span
                                                                        style="color: #2b303a; font-size: 20px;"><strong>'.$seguimiento.'</strong></span>
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col num6"
                                                style="display: table-cell; vertical-align: top; max-width: 320px; min-width: 318px; background-color: #f9f3fa; width: 292px;">
                                                <div class="col_cont" style="width:100% !important;">
                                                    <div
                                                        style="border-top:0px solid transparent; border-left:8px solid #FFF; border-bottom:0px solid transparent; border-right:20px solid #FFF; padding-top:0px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;">
                                                        <table border="0" cellpadding="0" cellspacing="0" class="divider"
                                                            role="presentation"
                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                            valign="top" width="100%">
                                                            <tbody>
                                                                <tr style="vertical-align: top;" valign="top">
                                                                    <td class="divider_inner"
                                                                        style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;"
                                                                        valign="top">
                                                                        <table align="center" border="0" cellpadding="0"
                                                                            cellspacing="0" class="divider_content"
                                                                            role="presentation"
                                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 4px solid PURPLE; width: 100%;"
                                                                            valign="top" width="100%">
                                                                            <tbody>
                                                                                <tr style="vertical-align: top;" valign="top">
                                                                                    <td style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                                                        valign="top"><span></span></td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                        <div
                                                            style="color:#555555;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.5;padding-top:35px;padding-right:5px;padding-bottom:40px;padding-left:5px;">
                                                            <div
                                                                style="line-height: 1.5; font-size: 12px; color: #555555; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 18px;">
                                                                <p
                                                                    style="font-size: 12px; line-height: 1.5; text-align: center; word-break: break-word; mso-line-height-alt: 18px; margin: 0;">
                                                                    <span
                                                                        style="color: #a2a9ad; font-size: 12px;"><strong>TOTAL</strong></span>
                                                                </p>
                                                                <p
                                                                    style="font-size: 20px; line-height: 1.5; text-align: center; word-break: break-word; mso-line-height-alt: 30px; margin: 0;">
                                                                    <span
                                                                        style="color: #2b303a; font-size: 20px;"><strong>$'.$ammount.'</strong></span>
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div style="background-color:transparent;">
                                    <div class="block-grid"
                                        style="min-width: 320px; max-width: 640px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #fff;">
                                        <div style="border-collapse: collapse;display: table;width: 100%;background-color:#fff;">
                                            <div class="col num12"
                                                style="min-width: 320px; max-width: 640px; display: table-cell; vertical-align: top; width: 640px;">
                                                <div class="col_cont" style="width:100% !important;">
                                                    <div
                                                        style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:0px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;">
                                                        <table border="0" cellpadding="0" cellspacing="0" class="divider"
                                                            role="presentation"
                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                            valign="top" width="100%">
                                                            <tbody>
                                                                <tr style="vertical-align: top;" valign="top">
                                                                    <td class="divider_inner"
                                                                        style="word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 60px; padding-right: 0px; padding-bottom: 12px; padding-left: 0px;"
                                                                        valign="top">
                                                                        <table align="center" border="0" cellpadding="0"
                                                                            cellspacing="0" class="divider_content"
                                                                            role="presentation"
                                                                            style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid #BBBBBB; width: 100%;"
                                                                            valign="top" width="100%">
                                                                            <tbody>
                                                                                <tr style="vertical-align: top;" valign="top">
                                                                                    <td style="word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"
                                                                                        valign="top"><span></span></td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
 
                                <div style="background-color:transparent;">
                                    <div class="block-grid"
                                        style="min-width: 320px; max-width: 640px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; Margin: 0 auto; background-color: #2b303a;">
                                        <div style="border-collapse: collapse;display: table;width: 100%;background-color:#2b303a;">
                                            <div class="col num12"
                                                style="min-width: 320px; max-width: 640px; display: table-cell; vertical-align: top; width: 640px;">
                                                <div class="col_cont" style="width:100% !important;">
                                                    <div
                                                        style="border-top:0px solid transparent; border-left:0px solid transparent; border-bottom:0px solid transparent; border-right:0px solid transparent; padding-top:0px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;">
                                                        <div
                                                            style="color:#f8f8f9;font-family:Ubuntu, Tahoma, Verdana, Segoe, sans-serif;line-height:1.5;padding-top:20px;padding-right:10px;padding-bottom:10px;padding-left:10px;">
                                                            <div
                                                                style="line-height: 1.5; font-size: 12px; font-family: Ubuntu, Tahoma, Verdana, Segoe, sans-serif; color: #f8f8f9; mso-line-height-alt: 18px;">
                                                                <p
                                                                    style="font-size: 14px; line-height: 1.5; word-break: break-word; text-align: center; font-family: Ubuntu, Tahoma, Verdana, Segoe, sans-serif; mso-line-height-alt: 21px; margin: 0;">
                                                                    <strong>HOME PACK CHILE SPA</strong></p>
                                                            </div>
                                                        </div>
                                                        <div
                                                            style="color:#555555;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.2;padding-top:20px;padding-right:40px;padding-bottom:30px;padding-left:40px;">
                                                            <div
                                                                style="line-height: 1.2; font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; color: #555555; mso-line-height-alt: 14px;">
                                                                <p
                                                                    style="font-size: 12px; line-height: 1.2; word-break: break-word; text-align: left; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 14px; margin: 0;">
                                                                    <span style="color: #95979c; font-size: 12px;">Home Pack Chile
                                                                        Copyright © 2020</span></p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </body>
            
            </html>
        ');

        $mail->send();
    } catch (Exception $e) {
        // echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }
}
?>