<?php
//Verifying the Signature
$recievedJwt = $_GET['token'];
$secret_key = 'HOMEPACKYITP2020';
// Split a string by '.' 
$jwt_values = explode('.', $recievedJwt);
// extracting the signature from the original JWT 
$recieved_signature = $jwt_values[2];
// concatenating the first two arguments of the $jwt_values array, representing the header and the payload
$recievedHeaderAndPayload = $jwt_values[0] . '.' . $jwt_values[1];
// creating the Base 64 encoded new signature generated by applying the HMAC method to the concatenated header and payload values
$resultedsignature = base64_encode(hash_hmac('sha256', $recievedHeaderAndPayload, $secret_key, true));
// checking if the created signature is equal to the received signature
$recieved_signature = str_replace(" ", "+", $recieved_signature);
if($resultedsignature == $recieved_signature) {
    require_once __DIR__ . '/vendor/autoload.php';
    include("../api-yitp/conn.php");
    
    $filename = "BOLETA";
    $today = date("F j, Y, g:i a");
    $ciudades = [
            '1' => "Valparaiso",
            '2' => "Concon",
            '3' => "Puchuncavi",
            '4' => "Quintero",
            '5' => "Viña del Mar",
            '6' => "Quilpue",
            '7' => "Villa Alemana",
            '8' => "Peña Blanca",
            '9' => "Limache",
            '10' => "Olmue",
            '11' => "Quillota",
            '12' => "La cruz",
            '13' => "La calera",
            '14' => "Nogales",
            '15' => "Hijuelas",
            '16' => "La ligua",
            '17' => "Papudo",
            '18' => "Cabildo",
            '19' => "Los Andes",
            '20' => "San Felipe",
            '21' => "Llay Llay",
            '22' => "Panquehue",
            '23' => "San Antonio",
            '24' => "Algarrobo",
            '25' => "Cartagena",
            '26' => "El Quisco",
            '27' => "El Tabo",
            '28' => "Santo Domingo",
            '29' => "Santiago"
        ];
    $order = $_GET["orden_compra"];
    $fecha = "";
    $html='';
    $total = 0;
    $estado = "";
    $sql = "SELECT id, data, created_at, estado, transaction FROM pagos WHERE orden_compra = '$order'";
    $result = $conn->query($sql);
    if ($result->num_rows > 0) {
      while($row_p = $result->fetch_assoc()) {
        $transaction = json_decode($row_p["transaction"], true);
        $fecha = $row_p["created_at"];
        $estado = $row_p["estado"];
        
        $sql_despachos = "SELECT * FROM despachos WHERE orden_compra = '$order';";
        $despachos = $conn->query($sql_despachos);
        
        if ($despachos->num_rows > 0) {
          while($row = $despachos->fetch_assoc()) {
                $origen = $row["origen"];
                $destino = $row["destino"];
                $peso = "";
                if($row["peso"] == 0) {
                    $peso = "0 - 1,5 kg";
                }
                if($row["peso"] == 300) {
                    $peso = "1,51 - 3 kg";
                }
                if($row["peso"] == 600) {
                    $peso = "3,01 - 5 kg";
                }
                if($row["peso"] == 900) {
                    $peso = "5,01 - 10 kg";
                }
                if($row["peso"] == 1200) {
                    $peso = "10,01 - 15 kg";
                }
                $total = $total + $row["total"];
                $html .='   <tr>
                                <td style="text-align: center; padding: 8px;">'.$ciudades[$origen].'</td>
                                <td style="text-align: center; padding: 8px;">'.$ciudades[$destino].'</td>
                                <td style="text-align: center; padding: 8px;">'.$row["total"].'</td>
                            </tr>
                ';
          }
        }
      }
    }
    
    $html .= "<tr><td style='border-top: 1px solid black; padding: 8px;'></td></td><td style='border-top: 1px solid black; padding: 8px;'></td><td style='text-align: center; border-top: 1px solid black; padding: 8px;'>$total</td></tr></table><div style='text-align: center;'><br><h3>¡GRACIAS POR SU COMPRA!</h3><div style='background-color: green; color: white; padding: 8px; width: 160px; margin: 0 auto;  letter-spacing: 4px;'><b><span>".strtoupper($estado)."</span></b></div></div></div>";
    
    $mpdf = new \Mpdf\Mpdf();
    $mpdf->SetHTMLHeader("<div style='text-align: right;'>Home Pack Chile SPA.</div>");
    $mpdf->WriteHTML('<style>body { font-family: "arial"; }</style><div class="main-container">
                <br>
                <div style="text-align: center; width: 100%;"><img src="https://homepackchile.cl/wp-content/uploads/2020/11/c0ca13fe-9f21-4506-b4ea-89707923588b.png" width="120" style="margin-bottom: 50px;"/></div>
                <span><b>ID del pago: </b>'.$transaction["payment_id"].'</span><br>
                <span><b>Fecha del pago: </b>'.$fecha.'</span><br>
                <span><b>Monto: </b>$'.$transaction["amount"].'</span><br>
                <span><b>Orden de compra: </b>'.$order.'</span><br><br>
                <table width="100%" style="margin-top: 40px; margin-bottom: 50px; border-collapse: collapse;">
                    <thead>
                        <tr>
                            <th>Origen</th>
                            <th>Destino</th>
                            <th>Total</th>
                        </tr>
                    </thead>
    '. $html);
    
    $mpdf->Output("BOLETA_".$order, "D");
} else {
    echo "No permitido";
}