<?php
    include("./conn.php");
    
    //Verifying the Signature
    $recievedJwt = $_GET['token'];
    $secret_key = 'HOMEPACKYITP2020';
    // Split a string by '.' 
    $jwt_values = explode('.', $recievedJwt);
    // extracting the signature from the original JWT 
    $recieved_signature = $jwt_values[2];
    // concatenating the first two arguments of the $jwt_values array, representing the header and the payload
    $recievedHeaderAndPayload = $jwt_values[0] . '.' . $jwt_values[1];
    // creating the Base 64 encoded new signature generated by applying the HMAC method to the concatenated header and payload values
    $resultedsignature = base64_encode(hash_hmac('sha256', $recievedHeaderAndPayload, $secret_key, true));
    // checking if the created signature is equal to the received signature
    $recieved_signature = str_replace(" ", "+", $recieved_signature);
    if($resultedsignature == $recieved_signature) {
        $id = $_GET["id"];
        $total = 0;
        if (isset($_GET['pagina'])) {
            $page = $_GET['pagina'];
        } else {
            $page = 1;
        }
        $no_of_records_per_page = $_GET['cantidad'];
        $offset = ($page-1) * $no_of_records_per_page;
        
        $search = $_GET['search'];
        $count = $conn->query("SELECT COUNT(*) AS countDespachos FROM despachos WHERE id_usuario = $id AND (orden_compra LIKE '%$search%' OR numero_seguimiento LIKE '%$search%');");
        $fila = $count->fetch_assoc();
        $total = $fila['countDespachos'];
        
        $count->close();
        
        $despachos = array();
        
        $result = $conn->query("
            SELECT 	despachos.id as 'id', despachos.rut_destinatario as 'rut_destinatario', despachos.nombre_destinatario as 'nombre_destinatario', despachos.telefono_destinatario as 'telefono_destinatario', despachos.email_destinatario as 'email_destinatario', despachos.fecha_ingreso as 'fecha_ingreso', despachos.detalle as 'detalle', despachos.numero_seguimiento as 'numero_seguimiento', despachos.total as 'total', despachos.origen as 'origen', despachos.destino as 'destino', despachos.id_usuario as 'id_usuario', despachos.peso as 'peso', despachos.orden_compra as 'orden_compra', despachos.qr as 'qr', despachos.referencia as 'referencia', despachos.direccion as 'direccion', despachos.rut_remitente as 'rut_remitente', despachos.nombre_remitente as 'nombre_remitente', despachos.telefono_remitente as 'telefono_remitente', despachos.email_remitente as 'email_remitente', despachos.direccion_remitente as 'direccion_remitente', despachos.retirado as 'retirado', despachos.barcode as 'barcode', pagos.estado as 'pago', usuarios.nombre as 'chofer', despachos.entregado as 'entregado', despachos.centro_distribucion as 'centro_distribucion'
            FROM despachos 
            LEFT JOIN pagos
            ON despachos.id_pago = pagos.id
            LEFT JOIN usuarios
            ON despachos.id_chofer = usuarios.id
            WHERE despachos.id_usuario = $id 
            AND (despachos.orden_compra LIKE '%$search%' OR despachos.numero_seguimiento LIKE '%$search%') 
            ORDER BY fecha_ingreso DESC
            LIMIT $offset, $no_of_records_per_page;"
        );
        
        while ( $row = $result->fetch_assoc())  {
            $despachos[] = array(
                'id' => $row["id"], 
                'rut_destinatario' => $row["rut_destinatario"], 
                'nombre_destinatario' => $row["nombre_destinatario"], 
                'telefono_destinatario' => $row["telefono_destinatario"], 
                'email_destinatario' => $row["email_destinatario"], 
                'fecha_ingreso' => $row["fecha_ingreso"],
                'detalle' => $row["detalle"],
                'numero_seguimiento' => $row["numero_seguimiento"],
                'total' => $row["total"],
                'origen' => $row["origen"],
                'destino' => $row["destino"],
                'id_usuario' => $row["id_usuario"],
                'peso' => $row["peso"],
                'orden_compra' => $row["orden_compra"],
                'qr' => $row["qr"],
                'referencia' => $row["referencia"],
                'direccion' => $row["direccion"],
                'rut_remitente' => $row["rut_remitente"],
                'nombre_remitente' => $row["nombre_remitente"],
                'telefono_remitente' => $row["telefono_remitente"],
                'email_remitente' => $row["email_remitente"],
                'direccion_remitente' => $row["direccion_remitente"],
                'retirado' => $row["retirado"],
                'chofer' => $row["chofer"],
                'barcode' => $row["barcode"],
                'pago' => $row["pago"],
                'entregado' => $row["entregado"],
                'centro_distribucion' => $row["centro_distribucion"]
            );
        }
        $myObj->data = $despachos;
        $myObj->total = $total;
        $myJSON = json_encode($myObj);
        echo $myJSON;
    } else {
        echo "No permitido";
    }
?>