<?php
    include("./conn.php");
    
    //Verifying the Signature
    $recievedJwt = $_GET['token'];
    $secret_key = 'HOMEPACKYITP2020';
    // Split a string by '.' 
    $jwt_values = explode('.', $recievedJwt);
    // extracting the signature from the original JWT 
    $recieved_signature = $jwt_values[2];
    // concatenating the first two arguments of the $jwt_values array, representing the header and the payload
    $recievedHeaderAndPayload = $jwt_values[0] . '.' . $jwt_values[1];
    // creating the Base 64 encoded new signature generated by applying the HMAC method to the concatenated header and payload values
    $resultedsignature = base64_encode(hash_hmac('sha256', $recievedHeaderAndPayload, $secret_key, true));
    // checking if the created signature is equal to the received signature
    $recieved_signature = str_replace(" ", "+", $recieved_signature);
    if($resultedsignature == $recieved_signature) {
        $usuarios = array();
        
        $result = $conn->query("SELECT id, nombre, usuario, telefono, perfil, rut, email
                                FROM usuarios
                                WHERE perfil = 'chofer';"
                            );
        
        while ( $row = $result->fetch_assoc())  {
            $usuarios[] = array(
                'id' => $row["id"], 
                'nombre' => $row["nombre"], 
                'usuario' => $row["usuario"], 
                'telefono' => $row["telefono"], 
                'perfil' => $row["perfil"], 
                'rut' => $row["rut"],
                'email' => $row["email"]
            );
        }
        $myObj->data = $usuarios;
        $myJSON = json_encode($myObj);
        echo $myJSON;
    } else {
        echo "No permitido";
    }
?>