<?php
    include("./conn.php");
    
    //Verifying the Signature
    $recievedJwt = $_GET['token'];
    $secret_key = 'HOMEPACKYITP2020';
    // Split a string by '.' 
    $jwt_values = explode('.', $recievedJwt);
    // extracting the signature from the original JWT 
    $recieved_signature = $jwt_values[2];
    // concatenating the first two arguments of the $jwt_values array, representing the header and the payload
    $recievedHeaderAndPayload = $jwt_values[0] . '.' . $jwt_values[1];
    // creating the Base 64 encoded new signature generated by applying the HMAC method to the concatenated header and payload values
    $resultedsignature = base64_encode(hash_hmac('sha256', $recievedHeaderAndPayload, $secret_key, true));
    // checking if the created signature is equal to the received signature
    $recieved_signature = str_replace(" ", "+", $recieved_signature);
    if($resultedsignature == $recieved_signature) {
        if (isset($_GET['pagina'])) {
        $page = $_GET['pagina'];
        } else {
            $page = 1;
        }
        $id = $_GET["id"];
        $tipo = $_GET["tipo"];
        $estado = $_GET["estado"];
        $inicio = $_GET["inicio"];
        $fin = $_GET["fin"];
        $pagos = array();
        $total = 0;
        $no_of_records_per_page = $_GET['cantidad'];
        $offset = ($page-1) * $no_of_records_per_page;
        
        if($tipo == "admin" || $tipo == "chofer") {
            
            $filter_estado = "";
            
            if($estado != "null") {
                $filter_estado = "pagos.estado LIKE '%$estado%' AND ";
            } else {
                $filter_estado = "";
            }
            
            $filter_date = "";
            
            if($inicio != "null" && $fin != "null") {
                $filter_date = "DATE(pagos.created_at) >= '$inicio' AND DATE(pagos.created_at) <= '$fin' AND ";
            } else {
                $filter_date = "";
            }
            
            $search = $_GET['search'];
            
            $count = $conn->query("
                SELECT COUNT(*) AS countPagos 
                FROM pagos 
                LEFT JOIN usuarios 
                ON pagos.fk_id_usuario = usuarios.id 
                WHERE $filter_date $filter_estado (pagos.orden_compra LIKE '%$search%' OR usuarios.nombre LIKE '%$search%' OR usuarios.rut LIKE '%$search%')"
            );
            
            $fila = $count->fetch_assoc();
            $total = $fila['countPagos'];
            $count->close();
            
            $result = $conn->query("
                    SELECT pagos.id, pagos.orden_compra, pagos.estado, pagos.total, pagos.created_at, pagos.fk_id_usuario, pagos.transaction, usuarios.nombre as 'nombre', usuarios.rut as 'rut', pagos.data as 'data', pagos.medio as 'medio'
                    FROM pagos 
                    LEFT JOIN usuarios 
                    ON pagos.fk_id_usuario = usuarios.id 
                    WHERE $filter_date $filter_estado (pagos.orden_compra LIKE '%$search%' OR usuarios.nombre LIKE '%$search%' OR usuarios.rut LIKE '%$search%') 
                    ORDER BY created_at DESC
                    LIMIT $offset, $no_of_records_per_page;"
                );

            
        } else {
            $filter_estado = "";
            
            if($estado != "null") {
                $filter_estado = "pagos.estado LIKE '%$estado%' AND ";
            } else {
                $filter_estado = "";
            }
            
            $filter_date = "";
            
            if($inicio != "null" && $fin != "null") {
                $filter_date = "DATE(pagos.created_at) >= '$inicio' AND DATE(pagos.created_at) <= '$fin' AND ";
            } else {
                $filter_date = "";
            }
            
            $search = $_GET['search'];
            
            $count = $conn->query("
                SELECT COUNT(*) AS countPagos 
                FROM pagos 
                LEFT JOIN usuarios 
                ON pagos.fk_id_usuario = usuarios.id 
                WHERE $filter_date $filter_estado (pagos.orden_compra LIKE '%$search%' OR usuarios.nombre LIKE '%$search%' OR usuarios.rut LIKE '%$search%')
                AND pagos.fk_id_usuario = $id"
            );
            
            $fila = $count->fetch_assoc();
            $total = $fila['countPagos'];
            $count->close();
            
            $result = $conn->query(
                "SELECT pagos.id, pagos.orden_compra, pagos.estado, pagos.total, pagos.created_at, pagos.fk_id_usuario, pagos.transaction, usuarios.nombre as 'nombre', usuarios.rut as 'rut', pagos.data as 'data', pagos.medio as 'medio'
                FROM pagos 
                LEFT JOIN usuarios 
                ON pagos.fk_id_usuario = usuarios.id 
                WHERE $filter_date $filter_estado (pagos.orden_compra LIKE '%$search%' OR usuarios.nombre LIKE '%$search%' OR usuarios.rut LIKE '%$search%')
                AND pagos.fk_id_usuario = $id 
                ORDER BY created_at DESC
                LIMIT $offset, $no_of_records_per_page;"
            );
        }
        
        while ( $row = $result->fetch_assoc())  {
            $pagos[] = array(
                'id' => $row["id"], 
                'orden_compra' => $row["orden_compra"], 
                'estado' => $row["estado"], 
                'total' => $row["total"], 
                'created_at' => $row["created_at"], 
                'fk_id_usuario' => $row["fk_id_usuario"],
                'transaction' => $row["transaction"],
                'nombre' => $row["nombre"],
                'rut' => $row["rut"],
                'data' => $row["data"],
                'medio' => $row["medio"],
            );
        }
        $myObj->data = $pagos;
        $myObj->total = $total;
        $myJSON = json_encode($myObj);
        echo $myJSON;
    } else {
        echo "No permitido";
    }
?>