<?php
    include("./conn.php");
    
    //Verifying the Signature
    $recievedJwt = $_GET['token'];
    $secret_key = 'HOMEPACKYITP2020';
    // Split a string by '.' 
    $jwt_values = explode('.', $recievedJwt);
    // extracting the signature from the original JWT 
    $recieved_signature = $jwt_values[2];
    // concatenating the first two arguments of the $jwt_values array, representing the header and the payload
    $recievedHeaderAndPayload = $jwt_values[0] . '.' . $jwt_values[1];
    // creating the Base 64 encoded new signature generated by applying the HMAC method to the concatenated header and payload values
    $resultedsignature = base64_encode(hash_hmac('sha256', $recievedHeaderAndPayload, $secret_key, true));
    // checking if the created signature is equal to the received signature
    $recieved_signature = str_replace(" ", "+", $recieved_signature);
    if($resultedsignature == $recieved_signature) {
        $numero_seguimiento = $_GET["numero_seguimiento"];
        $despachos = array();
        $result = $conn->query("SELECT id, orden_compra FROM despachos WHERE numero_seguimiento = $numero_seguimiento;");
        while ( $row = $result->fetch_assoc())  {
            $result = $conn->query("SELECT total FROM pagos WHERE orden_compra = '".$row["orden_compra"]."';");
            while ( $pago = $result->fetch_assoc())  {
                $despachos[] = array(
                    'id' => $row["id"],
                    'orden_compra' => $row["orden_compra"],
                    'total' => $pago["total"]
                );
            }
        }
        echo json_encode($despachos);
    } else {
        echo "No permitido";
    }
?>